title: How to connect a servo motor to a Crumble using jumper cables
hero_image: images/banner.png
description: How to connect a servo motor to a Crumble using jumper cables
version: 5
listed: false
copyedit: false
last_tested: "2019-05-22"
steps:
  - title: How to connect a servo motor to a Crumble using jumper cables
